### ISSUE TITLE
In some cases, Node Composer could not order the Isolate Composer to instantiate components

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#41]
Observed in : *Cohoret 1.1.0.pre1*

**Exceptions in Node Composer side**:

`````
2015-06-26 15:34:20,077:ERROR:cohorte.composer.node.commander: Error calling composer on isolate serverrendezvous: No listener for 0D8E6AE077EE472DB8D4B5758330CAAB (herald/rpc/jabsorbrpc)
Traceback (most recent call last):
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/cohorte/composer/node/commander.py", line 228, in __push_orders
    composer.instantiate(components)
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/herald/remote/herald_jabsorbrpc.py", line 234, in __call__
    reply_message = self.__send(self.__peer, self.__subject, request)
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/herald/remote/herald_jabsorbrpc.py", line 269, in __call
    return self._herald.send(peer, beans.Message(subject, content))
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/herald/core.py", line 793, in send
    if event.wait(timeout):
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/pelix/utilities.py", line 525, in wait
    raise self.__exception
herald.exceptions.NoListener: No listener for 0D8E6AE077EE472DB8D4B5758330CAAB (herald/rpc/jabsorbrpc)
``````

**This could be explained as follow**:

- JabsorbRpcExporter (which provides IMessageListener and IServiceExporter services) when becomes valid, the Remote Services Dispatcher consume the service and informs others about the service using Herald Discovery.
- It happens that the message is transported, and traited by other peers before that the binding between Herald core and the JabsorbRpcExporter (message listener) is done. And this what explain the exception.

**To avoid this problem**: 

- We should not send the dispatcher message until that the binding between herald core and JabsorbRpcExporter is done. 
- We can for instance add a requires on JabsorbRpcExporter to Herald, which will avoid exporting the JabsorbRpcExporter services until Herald will be active. And we hope that Herald consume this servive before the activation of the dispatcher and sending of the message.

**Comment by tcalmant** [comment]
This problem seems to appear only on the Java version of Herald.

To ensure that JabsorbRPCExporter can receive messages before exporting services:

1. JabsorbRPCExporter must depend (``@Requires``) on the Herald core service: it will be ready to consume message listeners before the exporter is validated
2. At first, JabsorbRPCExporter must provide the message listener service only.
This will ensure that the Herald Core component will consume it right after the validation of the exporter.
3. Add a ``@PostRegistration`` callback (see [iPOJO Documentation](http://felix.apache.org/documentation/subprojects/apache-felix-ipojo/apache-felix-ipojo-userguide/describing-components/providing-osgi-services.html#being-notified-of-the-service-registration-and-unregistration)) where the ``IServiceExporter`` service will be registered manually, i.e. using ``BundleContext.registerService``.
That way, JabsorbRPCExporter is ensured to receive messages before creating endpoints.
4. Add a ``@PreUnregistration`` callback (see [iPOJO Documentation](http://felix.apache.org/documentation/subprojects/apache-felix-ipojo/apache-felix-ipojo-userguide/describing-components/providing-osgi-services.html#being-notified-of-the-service-registration-and-unregistration)) where the ``IServiceExporter`` service must be unregistered.
Again, we then ensure that the exported services will be deleted and that the associated discovery events will be sent, before being unable to receive messages from Herald.
